global:
  scrape_interval: 5s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  scrape_timeout: 5s # Default value
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: 'ktor-example'
    metrics_path: '/metrics-micrometer'
    static_configs:
      - targets: [ 'ktor-example:8080' ]
        labels:
          framework: ktor-example

  - job_name: 'spring-example'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'spring-example:8080' ]
        labels:
          framework: spring-example
