name: Release to Sonatype

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version of the release"
        required: true
      branch:
        description: "Branch to release from"
        required: true
        default: 'main'

env:
  ORG_GRADLE_PROJECT_version: ${{ github.event.inputs.version }}
  ORG_GRADLE_PROJECT_ossrhPassword: ${{ secrets.SONATYPE_PASSWORD }}
  ORG_GRADLE_PROJECT_ossrhUsername: ${{ secrets.SONATYPE_USERNAME }}
  ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_SECRET }}
  ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_PASSPHRASE }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
    - name: Gradle Build
      uses: gradle/gradle-build-action@6095a76664413da4c8c134ee32e8a8ae900f0f1f
      with:
        arguments: build
    - name: Gradle Publish
      run: ./gradlew publishMavenPublicationToSonaTypeRepository
