name: Release to Sonatype

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version of the release"
        required: true
      branch:
        description: "Branch to release from"
        required: true
        default: 'main'

env:
  ORG_GRADLE_PROJECT_version: ${{ github.event.inputs.version }}
  ORG_GRADLE_PROJECT_ossrhPassword: ${{ secrets.SONATYPE_PASSWORD }}
  ORG_GRADLE_PROJECT_ossrhUsername: ${{ secrets.SONATYPE_USERNAME }}
  ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_SECRET }}
  ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_PASSPHRASE }}

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
    - name: Gradle Build
      uses: gradle/gradle-build-action@842c587ad8aa4c68eeba24c396e15af4c2e9f30a
      with:
        arguments: build --info
    - name: Gradle Publish
      run: ./gradlew publishMavenPublicationToSonaTypeRepository
    - uses: actions/upload-artifact@v3
      with:
        name: release ${{ github.event.inputs.version }}
        path: expiration-monitoring-*/build/libs/
